/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ApiPublicV1DeployRouteImport } from './routes/api/public/v1/deploy'
import { Route as RepoIdEditSplatRouteImport } from './routes/repo.$id.edit.$'
import { Route as ApiPublicLiveSlugSplatRouteImport } from './routes/api/public/live.$slug.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DeployRoute = ApiPublicV1DeployRouteImport.update({
  id: '/api/public/v1/deploy',
  path: '/api/public/v1/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoIdEditSplatRoute = RepoIdEditSplatRouteImport.update({
  id: '/repo/$id/edit/$',
  path: '/repo/$id/edit/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveSlugSplatRoute = ApiPublicLiveSlugSplatRouteImport.update({
  id: '/api/public/live/$slug/$',
  path: '/api/public/live/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/d/$slug': typeof DSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/v1/deploy': typeof ApiPublicV1DeployRoute
  '/repo/$id/edit/$': typeof RepoIdEditSplatRoute
  '/api/public/live/$slug/$': typeof ApiPublicLiveSlugSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/d/$slug': typeof DSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/v1/deploy': typeof ApiPublicV1DeployRoute
  '/repo/$id/edit/$': typeof RepoIdEditSplatRoute
  '/api/public/live/$slug/$': typeof ApiPublicLiveSlugSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/d/$slug': typeof DSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/v1/deploy': typeof ApiPublicV1DeployRoute
  '/repo/$id/edit/$': typeof RepoIdEditSplatRoute
  '/api/public/live/$slug/$': typeof ApiPublicLiveSlugSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/d/$slug'
    | '/r/$slug'
    | '/api/public/v1/deploy'
    | '/repo/$id/edit/$'
    | '/api/public/live/$slug/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/d/$slug'
    | '/r/$slug'
    | '/api/public/v1/deploy'
    | '/repo/$id/edit/$'
    | '/api/public/live/$slug/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/d/$slug'
    | '/r/$slug'
    | '/api/public/v1/deploy'
    | '/repo/$id/edit/$'
    | '/api/public/live/$slug/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DSlugRoute: typeof DSlugRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicV1DeployRoute: typeof ApiPublicV1DeployRoute
  RepoIdEditSplatRoute: typeof RepoIdEditSplatRoute
  ApiPublicLiveSlugSplatRoute: typeof ApiPublicLiveSlugSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/deploy': {
      id: '/api/public/v1/deploy'
      path: '/api/public/v1/deploy'
      fullPath: '/api/public/v1/deploy'
      preLoaderRoute: typeof ApiPublicV1DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$id/edit/$': {
      id: '/repo/$id/edit/$'
      path: '/repo/$id/edit/$'
      fullPath: '/repo/$id/edit/$'
      preLoaderRoute: typeof RepoIdEditSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live/$slug/$': {
      id: '/api/public/live/$slug/$'
      path: '/api/public/live/$slug/$'
      fullPath: '/api/public/live/$slug/$'
      preLoaderRoute: typeof ApiPublicLiveSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DSlugRoute: DSlugRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicV1DeployRoute: ApiPublicV1DeployRoute,
  RepoIdEditSplatRoute: RepoIdEditSplatRoute,
  ApiPublicLiveSlugSplatRoute: ApiPublicLiveSlugSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
